baseURL = '/'
languageCode = 'en-us'
title = 'Coding Ninja Journey'
theme = "beautifulhugo"

[Params]
mainSections = ["post", "posts"]
logo = "images/CodingNinjaJourney-Logo.png"

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[[menu.main]]
name = "About"
url = "page/about"
weight = 1
