baseURL = '/'
languageCode = 'en-us'
title = 'Coding Ninja Journey'
theme = "beautifulhugo"

[Params]
mainSections = ["post", "posts"]
logo = "images/CodingNinjaJourney-Logo.png"

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "pages/about"
weight = 1

[[menu.main]]
name = "Home"
url = "/"
weight = 1
